In [31]:
from tqdm import tqdm
import pandas as pd
import numpy as np
import datetime

In [2]:
def price_table(yr):
    path=r'price/아파트(매매)_실거래가_{}.xlsx'.format(yr)
    price_title = pd.read_excel(path, sheet_name = '아파트 매매 실거래가')
    return price_title

In [3]:
%%time
d={}
for i in tqdm(range(2006,2020)):
    d['price_{}'.format(i)] = price_table(i)
    
#     price_title = 'price_'+ '{}'.format(i)
# #     price_table(i)
#     'price_{0}'.format(i) = price_table(i)

100%|██████████| 14/14 [01:56<00:00,  8.30s/it]

CPU times: user 1min 55s, sys: 588 ms, total: 1min 55s
Wall time: 1min 56s

In [4]:
d

{'price_2006':                   시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200603   10
 1       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200603   29
 2       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200604   29
 3       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200606    1
 4       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200610   20
 ...               ...     ...  ...  ..             ...      ...     ...  ...
 120796  서울특별시 중랑구 중화동     450  450   0             한신2    84.03  200612   19
 120797  서울특별시 중랑구 중화동  274-51  274  51         한영(101)    57.66  200605   18
 120798  서울특별시 중랑구 중화동  274-75  274  75         한영(102)    66.54  200611   17
 120799  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    68.32  200609   11
 120800  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    68.32  200611   28

               거래금액(만원)  층  건축년도         도로명
 0               59,500  7  1988     언주로 103
 1               60,000  6  1988     언주로 103
 2               67,000  9  1988     언주로 103
 3               60,000  4  1988     언주로 103
 4               72,250  5  1988     언주로 103
 ...                ... ..   ...         ...
 120796          32,500  6  1998     동일로 752
 120797          12,100  5  2003  동일로144길 74
 120798          13,000  5  2003  동일로144길 74
 120799          13,000  3  2003  동일로144길 74
 120800          13,000  3  2003  동일로144길 74

 [120801 rows x 12 columns],
 'price_2007':                  시군구     번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  200711   13
 1      서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    79.97  200703    9
 2      서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    54.98  200703    9
 3      서울특별시 강남구 개포동    652  652   0          개포우성3차   104.43  200707   20
 4      서울특별시 강남구 개포동    652  652   0          개포우성3차   133.46  200711   22
 ...              ...    ...  ...  ..             ...      ...     ...  ...
 59026  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  200709    2
 59027  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    64.48  200711   10
 59028  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    80.23  200712   14
 59029  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  200712   19
 59030  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    64.48  200712   31

              거래금액(만원)  층  건축년도          도로명
 0              75,000  1  1988      언주로 103
 1              93,000  2  1987        언주로 3
 2              69,300  4  1987        언주로 3
 3              99,900  8  1984      개포로 307
 4             157,000  6  1984      개포로 307
 ...               ... ..   ...          ...
 59026          21,000  3  2007  봉화산로27가길 19
 59027          20,000  2  2007  봉화산로27가길 19
 59028          21,000  2  2007  봉화산로27가길 19
 59029          23,000  4  2007  봉화산로27가길 19
 59030          20,500  3  2007  봉화산로27가길 19

 [59031 rows x 12 columns],
 'price_2008':                  시군구     번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  200808   26
 1      서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  200812   11
 2      서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    79.97  200804   17
 3      서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    79.97  200805   10
 4      서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    79.97  200810    4
 ...              ...    ...  ...  ..             ...      ...     ...  ...
 57310  서울특별시 중랑구 중화동     11   11   0           현대휴앤미    95.94  200806   25
 57311  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  200803    7
 57312  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  200803   20
 57313  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    80.23  200804    2
 57314  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  200809   19

              거래금액(만원)  층  건축년도          도로명
 0              80,000  8  1988      언주로 103
 1              80,000  3  1988      언주로 103
 2              89,000  4  1987        언주로 3
 3              81,000  5  1987        언주로 3
 4              73,000  1  1987        언주로 3
 ...               ... ..   ...          ...
 57310          30,000  5  2007  봉화산로27가길 23
 57311          23,000  5  2007  봉화산로27가길 19
 57312          23,700  4  2007  봉화산로27가길 19
 57313          24,500  2  2007  봉화산로27가길 19
 57314          21,000  3  2007  봉화산로27가길 19

 [57315 rows x 12 columns],
 'price_2009':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  200904   17
 1      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  200902    9
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  200903    4
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    54.98  200904   26
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  200905   22
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 73652  서울특별시 중랑구 중화동  274-75  274  75         한영(102)    72.22  200904    7
 73653  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    73.80  200911    4
 73654  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    68.88  200912    7
 73655  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.20  200903   10
 73656  서울특별시 중랑구 중화동    11-7   11   7     현대휴앤미(102동)    77.71  200909    5

              거래금액(만원)  층  건축년도          도로명
 0              67,800  3  1988      언주로 103
 1              74,000  2  1987        언주로 3
 2              59,750  4  1987        언주로 3
 3              57,500  5  1987        언주로 3
 4              80,500  1  1987        언주로 3
 ...               ... ..   ...          ...
 73652          25,000  3  2003   동일로144길 74
 73653          23,000  5  2003   동일로144길 74
 73654          23,000  5  2003   동일로144길 74
 73655          32,500  3  2007  봉화산로27가길 23
 73656          26,800  3  2007  봉화산로27가길 19

 [73657 rows x 12 columns],
 'price_2010':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    54.98  201001   28
 1      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201008    5
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201008   25
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201009    2
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201012   28
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 44507  서울특별시 중랑구 중화동     450  450   0             한신2    84.03  201011    8
 44508  서울특별시 중랑구 중화동     450  450   0             한신2    84.03  201012    7
 44509  서울특별시 중랑구 중화동     450  450   0             한신2    84.03  201012   30
 44510  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    87.31  201006   22
 44511  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    67.57  201003    6

              거래금액(만원)   층  건축년도         도로명
 0              66,000   3  1987       언주로 3
 1              80,600   5  1987       언주로 3
 2              80,000   4  1987       언주로 3
 3              83,000   1  1987       언주로 3
 4              67,000   4  1987       언주로 3
 ...               ...  ..   ...         ...
 44507          37,300  13  1998     동일로 752
 44508          35,000   3  1998     동일로 752
 44509          35,700   3  1998     동일로 752
 44510          31,300   6  2003  동일로144길 74
 44511          26,000   4  2003  동일로144길 74

 [44512 rows x 12 columns],
 'price_2011':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201107    9
 1      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201107   28
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201101   19
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201109    2
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201112   17
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 54645  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    68.32  201107   12
 54646  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    75.88  201110    7
 54647  서울특별시 중랑구 중화동      11   11   0           현대휴앤미    82.17  201101   27
 54648  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.20  201105    3
 54649  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.17  201112    1

              거래금액(만원)  층  건축년도          도로명
 0              64,000  3  1988      언주로 103
 1              65,500  5  1988      언주로 103
 2              70,500  3  1987        언주로 3
 3              85,000  5  1987        언주로 3
 4              68,000  1  1987        언주로 3
 ...               ... ..   ...          ...
 54645          23,250  3  2003   동일로144길 74
 54646          21,700  2  2003   동일로144길 74
 54647          28,000  7  2007  봉화산로27가길 23
 54648          32,500  5  2007  봉화산로27가길 23
 54649          38,000  6  2007  봉화산로27가길 23

 [54650 rows x 12 columns],
 'price_2012':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201205    1
 1      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201207    9
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201212   26
 3      서울특별시 강남구 개포동     652  652   0          개포우성3차   104.43  201204   13
 4      서울특별시 강남구 개포동    12-2   12   2      개포자이(12-2)   134.30  201205    8
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 41064  서울특별시 중랑구 중화동     450  450   0             한신2    84.03  201207   25
 41065  서울특별시 중랑구 중화동     450  450   0             한신2    59.76  201212   10
 41066  서울특별시 중랑구 중화동  274-51  274  51         한영(101)    84.69  201212    3
 41067  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    58.46  201212   14
 41068  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.20  201212   20

              거래금액(만원)   층  건축년도          도로명
 0              66,000   4  1988      언주로 103
 1              58,000   2  1988      언주로 103
 2              55,700   3  1987        언주로 3
 3              85,000   6  1984      개포로 307
 4             119,500  14  2004   개포로109길 69
 ...               ...  ..   ...          ...
 41064          37,100  23  1998      동일로 752
 41065          23,600  23  1998      동일로 752
 41066          23,500   2  2003   동일로144길 74
 41067          22,000   3  2003   동일로144길 74
 41068          30,500   4  2007  봉화산로27가길 23

 [41069 rows x 12 columns],
 'price_2013':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201309    8
 1      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201312   16
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201302   11
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201302   22
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201305   10
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 68135  서울특별시 중랑구 중화동  274-51  274  51         한영(101)    76.12  201302   15
 68136  서울특별시 중랑구 중화동  274-75  274  75         한영(102)    72.22  201310   10
 68137  서울특별시 중랑구 중화동  274-75  274  75         한영(102)    46.84  201310   22
 68138  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    58.46  201306   26
 68139  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    68.32  201303   30

              거래금액(만원)  층  건축년도         도로명
 0              57,000  2  1988     언주로 103
 1              57,000  2  1988     언주로 103
 2              55,000  5  1987       언주로 3
 3              58,250  4  1987       언주로 3
 4              60,000  5  1987       언주로 3
 ...               ... ..   ...         ...
 68135          22,300  3  2003  동일로144길 74
 68136          23,700  4  2003  동일로144길 74
 68137          17,200  7  2003  동일로144길 74
 68138          20,000  2  2003  동일로144길 74
 68139          20,000  4  2003  동일로144길 74

 [68140 rows x 12 columns],
 'price_2014':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201401   29
 1      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201411   10
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201404    3
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201407   24
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    54.98  201408   29
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 85548  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    58.46  201412   18
 85549  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    70.96  201405   29
 85550  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    75.88  201407   29
 85551  서울특별시 중랑구 중화동      11   11   0           현대휴앤미    95.94  201402   14
 85552  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.20  201406   26

              거래금액(만원)  층  건축년도          도로명
 0              55,000  7  1988      언주로 103
 1              59,500  4  1988      언주로 103
 2              67,000  4  1987        언주로 3
 3              58,800  4  1987        언주로 3
 4              50,000  2  1987        언주로 3
 ...               ... ..   ...          ...
 85548          22,000  3  2003   동일로144길 74
 85549          24,300  3  2003   동일로144길 74
 85550          21,300  3  2003   동일로144길 74
 85551          26,250  2  2007  봉화산로27가길 23
 85552          28,300  6  2007  봉화산로27가길 23

 [85553 rows x 12 columns],
 'price_2015':                   시군구     번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0       서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  201501   11
 1       서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  201503    3
 2       서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  201503    7
 3       서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)    77.75  201508   16
 4       서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동    79.97  201501   29
 ...               ...    ...  ...  ..             ...      ...     ...  ...
 120050  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    77.71  201505    5
 120051  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    76.43  201505   19
 120052  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    67.36  201506    3
 120053  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    64.48  201507    1
 120054  서울특별시 중랑구 중화동   11-7   11   7     현대휴앤미(102동)    76.43  201510   13

               거래금액(만원)  층  건축년도          도로명
 0               60,000  5  1988      언주로 103
 1               65,000  5  1988      언주로 103
 2               62,500  2  1988      언주로 103
 3               68,000  6  1988      언주로 103
 4               73,000  5  1987        언주로 3
 ...                ... ..   ...          ...
 120050          27,500  4  2007  봉화산로27가길 19
 120051          26,900  6  2007  봉화산로27가길 19
 120052          24,950  6  2007  봉화산로27가길 19
 120053          26,000  3  2007  봉화산로27가길 19
 120054          28,250  7  2007  봉화산로27가길 19

 [120055 rows x 12 columns],
 'price_2016':                   시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201603   28
 1       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201604    2
 2       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201605    6
 3       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201605   19
 4       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201612   27
 ...               ...     ...  ...  ..             ...      ...     ...  ...
 110217  서울특별시 중랑구 중화동  274-51  274  51         한영(101)    84.69  201602   13
 110218  서울특별시 중랑구 중화동  274-51  274  51         한영(101)    84.69  201605   17
 110219  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    67.44  201610   25
 110220  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    67.57  201602    6
 110221  서울특별시 중랑구 중화동      11   11   0           현대휴앤미    95.94  201612    8

               거래금액(만원)  층  건축년도          도로명
 0               75,000  5  1988      언주로 103
 1               71,000  2  1988      언주로 103
 2               76,900  9  1988      언주로 103
 3               75,500  9  1988      언주로 103
 4               80,000  5  1988      언주로 103
 ...                ... ..   ...          ...
 110217          27,000  3  2003   동일로144길 74
 110218          30,000  4  2003   동일로144길 74
 110219          25,700  5  2003   동일로144길 74
 110220          22,300  2  2003   동일로144길 74
 110221          32,000  5  2007  봉화산로27가길 23

 [110222 rows x 12 columns],
 'price_2017':                   시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201703   15
 1       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201704   19
 2       서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201707    8
 3       서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201704   13
 4       서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201704   17
 ...               ...     ...  ...  ..             ...      ...     ...  ...
 105086  서울특별시 중랑구 중화동  274-75  274  75         한영(102)    72.22  201711   18
 105087  서울특별시 중랑구 중화동  274-76  274  76         한영(103)   125.09  201705   29
 105088  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    50.29  201708   17
 105089  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    87.31  201708   28
 105090  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    67.57  201711    4

               거래금액(만원)  층  건축년도         도로명
 0               80,000  7  1988     언주로 103
 1               85,000  2  1988     언주로 103
 2               89,900  1  1988     언주로 103
 3               97,500  4  1987       언주로 3
 4               98,000  1  1987       언주로 3
 ...                ... ..   ...         ...
 105086          28,300  4  2003  동일로144길 74
 105087          36,900  6  2003  동일로144길 74
 105088          19,100  5  2003  동일로144길 74
 105089          30,500  6  2003  동일로144길 74
 105090          25,100  4  2003  동일로144길 74

 [105091 rows x 12 columns],
 'price_2018':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201801    3
 1      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201801    8
 2      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201801   11
 3      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    79.97  201803   19
 4      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    54.98  201804    5
 ...              ...     ...  ...  ..             ...      ...     ...  ...
 81383  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    56.52  201809   22
 81384  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    69.52  201811    1
 81385  서울특별시 중랑구 중화동  274-76  274  76         한영(103)    69.09  201811   12
 81386  서울특별시 중랑구 중화동  274-77  274  77         한영(104)    75.88  201808   29
 81387  서울특별시 중랑구 중화동      11   11   0           현대휴앤미   100.17  201807   30

              거래금액(만원)  층  건축년도          도로명
 0             130,000  4  1987        언주로 3
 1             117,000  2  1987        언주로 3
 2             130,000  1  1987        언주로 3
 3             139,500  2  1987        언주로 3
 4             107,500  5  1987        언주로 3
 ...               ... ..   ...          ...
 81383          21,000  5  2003   동일로144길 74
 81384          29,500  3  2003   동일로144길 74
 81385          30,000  5  2003   동일로144길 74
 81386          24,500  2  2003   동일로144길 74
 81387          37,000  2  2007  봉화산로27가길 23

 [81388 rows x 12 columns],
 'price_2019':                  시군구      번지   본번  부번             단지명  전용면적(㎡)    계약년월  계약일  \
 0      서울특별시 강남구 개포동   655-2  655   2  개포2차현대아파트(220)    77.75  201906   18
 1      서울특별시 강남구 개포동   658-1  658   1  개포6차우성아파트1동~8동    67.28  201905    4

In [5]:
price_2006=d['price_2006']
price_2007=d['price_2007']
price_2008=d['price_2008']
price_2009=d['price_2009']
price_2010=d['price_2010']
price_2011=d['price_2011']
price_2012=d['price_2012']
price_2013=d['price_2013']
price_2014=d['price_2014']
price_2015=d['price_2015']
price_2016=d['price_2016']
price_2017=d['price_2017']
price_2018=d['price_2018']
price_2019=d['price_2019']

In [6]:
raw_data=pd.concat([price_2006, price_2007, price_2008, price_2009, price_2010,
           price_2011, price_2012, price_2013, price_2014, price_2015, 
            price_2016, price_2017, price_2018, price_2019], ignore_index=True,sort=False)
raw_data

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,10,"59,500",7,1988,언주로 103
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,29,"60,000",6,1988,언주로 103
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200604,29,"67,000",9,1988,언주로 103
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200606,1,"60,000",4,1988,언주로 103
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,20,"72,250",5,1988,언주로 103
...,...,...,...,...,...,...,...,...,...,...,...,...
1061830,서울특별시 중랑구 중화동,450,450,0,한신2,59.76,201908,8,"44,500",15,1998,동일로 752
1061831,서울특별시 중랑구 중화동,274-51,274,51,한영(101),84.69,201909,3,"35,000",7,2003,동일로144길 74
1061832,서울특별시 중랑구 중화동,274-75,274,75,한영(102),57.18,201905,20,"25,800",6,2003,동일로144길 74
1061833,서울특별시 중랑구 중화동,11,11,0,현대휴앤미,82.17,201901,31,"34,500",7,2007,봉화산로27가길 23
1061834,서울특별시 중랑구 중화동,11-7,11,7,현대휴앤미(102동),64.48,201907,15,"32,800",3,2007,봉화산로27가길 19

In [7]:
raw_data.columns

Index(['시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일', '거래금액(만원)',
       '층', '건축년도', '도로명'],
      dtype='object')

In [8]:
raw_data['시'] = raw_data['시군구'].str.split(" ").str[0]
raw_data['구'] = raw_data['시군구'].str.split(" ").str[1]
raw_data['동'] = raw_data['시군구'].str.split(" ").str[2]
raw_data.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,시,군,구
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,10,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,29,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200604,29,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200606,1,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,20,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동

In [9]:
filt = (raw_data['계약일']<10)
raw_data.loc[raw_data[filt].index, '계약일'] = '0' + raw_data['계약일'].astype(str)
raw_data.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,시,군,구
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,10,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,29,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200604,29,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200606,01,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,20,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동

In [10]:
raw_data['계약년월일']=raw_data['계약년월'].astype(str) + raw_data['계약일'].astype(str)
raw_data.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,시,군,구,계약년월일
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,10,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동,20060310
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,29,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동,20060329
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200604,29,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동,20060429
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200606,01,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동,20060601
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,20,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동,20061020

In [11]:
raw_data.head(20)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,시,군,구,계약년월일
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,10,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동,20060310
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200603,29,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동,20060329
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200604,29,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동,20060429
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200606,01,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동,20060601
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,20,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동,20061020
5,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200610,30,"73,500",8,1988,언주로 103,서울특별시,강남구,개포동,20061030
6,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),77.75,200612,09,"76,500",5,1988,언주로 103,서울특별시,강남구,개포동,20061209
7,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,67.28,200601,19,"54,500",3,1987,언주로 3,서울특별시,강남구,개포동,20060119
8,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200601,21,"67,000",3,1987,언주로 3,서울특별시,강남구,개포동,20060121
9,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200601,25,"67,500",4,1987,언주로 3,서울특별시,강남구,개포동,20060125
10,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200602,01,"66,000",5,1987,언주로 3,서울특별시,강남구,개포동,20060201
11,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200603,02,"68,000",5,1987,언주로 3,서울특별시,강남구,개포동,20060302
12,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,54.98,200603,08,"48,500",3,1987,언주로 3,서울특별시,강남구,개포동,20060308
13,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200603,10,"67,000",5,1987,언주로 3,서울특별시,강남구,개포동,20060310
14,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200603,11,"70,000",3,1987,언주로 3,서울특별시,강남구,개포동,20060311
15,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200603,20,"71,500",1,1987,언주로 3,서울특별시,강남구,개포동,20060320
16,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200604,20,"81,500",5,1987,언주로 3,서울특별시,강남구,개포동,20060420
17,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200605,09,"88,000",3,1987,언주로 3,서울특별시,강남구,개포동,20060509
18,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,67.28,200610,17,"75,000",4,1987,언주로 3,서울특별시,강남구,개포동,20061017
19,서울특별시 강남구 개포동,658-1,658,1,개포6차우성아파트1동~8동,79.97,200610,17,"88,000",4,1987,언주로 3,서울특별시,강남구,개포동,20061017

In [12]:
raw_data.drop(['시군구','계약년월','계약일'],1, inplace=True)
raw_data.head()

,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,시,군,구,계약년월일
0,655-2,655,2,개포2차현대아파트(220),77.75,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동,20060310
1,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동,20060329
2,655-2,655,2,개포2차현대아파트(220),77.75,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동,20060429
3,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동,20060601
4,655-2,655,2,개포2차현대아파트(220),77.75,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동,20061020

In [13]:
from datetime import datetime

In [14]:
raw_data['계약년월일'] = pd.to_datetime(raw_data['계약년월일'])

In [15]:
raw_data['연']=raw_data['계약년월일'].dt.year
raw_data['월']=raw_data['계약년월일'].dt.month
raw_data['일']=raw_data['계약년월일'].dt.day
raw_data.head()

,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,시,군,구,계약년월일,연,월,일
0,655-2,655,2,개포2차현대아파트(220),77.75,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동,2006-03-10,2006,3,10
1,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동,2006-03-29,2006,3,29
2,655-2,655,2,개포2차현대아파트(220),77.75,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동,2006-04-29,2006,4,29
3,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동,2006-06-01,2006,6,1
4,655-2,655,2,개포2차현대아파트(220),77.75,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동,2006-10-20,2006,10,20

In [16]:
raw_data['uid'] = raw_data['시'] + raw_data['군'] + raw_data['구'] + raw_data['단지명']
raw_data.head()

,번지,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,도로명,시,군,구,계약년월일,연,월,일,uid
0,655-2,655,2,개포2차현대아파트(220),77.75,"59,500",7,1988,언주로 103,서울특별시,강남구,개포동,2006-03-10,2006,3,10,서울특별시강남구개포동개포2차현대아파트(220)
1,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",6,1988,언주로 103,서울특별시,강남구,개포동,2006-03-29,2006,3,29,서울특별시강남구개포동개포2차현대아파트(220)
2,655-2,655,2,개포2차현대아파트(220),77.75,"67,000",9,1988,언주로 103,서울특별시,강남구,개포동,2006-04-29,2006,4,29,서울특별시강남구개포동개포2차현대아파트(220)
3,655-2,655,2,개포2차현대아파트(220),77.75,"60,000",4,1988,언주로 103,서울특별시,강남구,개포동,2006-06-01,2006,6,1,서울특별시강남구개포동개포2차현대아파트(220)
4,655-2,655,2,개포2차현대아파트(220),77.75,"72,250",5,1988,언주로 103,서울특별시,강남구,개포동,2006-10-20,2006,10,20,서울특별시강남구개포동개포2차현대아파트(220)

In [17]:
raw_data['단지명'].nunique()

7288

In [18]:
raw_data['단지명'].value_counts()

현대                12645
두산                 8743
한신                 8566
주공2                8145
신동아                7599
                  ...
(717-15)경원주택5동        1
A파크                   1
(791-18)              1
밀란체                   1
계영주택(746-49)          1
Name: 단지명, Length: 7288, dtype: int64

In [19]:
raw_data['단지명'].value_counts()[raw_data['단지명'].value_counts() < 10].index

Index(['경동미르웰', '대치하나빌', '방배2차상지리츠빌', '한아(987-21)', '방배아펠바움', '삼성그랑빌',
       '(246-11)', '리치빌(177-2)', '장안트윈A(306-8)', '미래하이츠',
       ...
       '은평뉴타운 박석고개(힐스테이트12단지임대)', '명수대', '(749-44)', '대호드림빌(38-213)', '휘경 SK뷰',
       '(717-15)경원주택5동', 'A파크', '(791-18)', '밀란체', '계영주택(746-49)'],
      dtype='object', length=1506)

In [20]:
raw_data['uid'].nunique()

8584

#### 서울특별시의 아파트 단지수는 2,404 
- cf. [K-apt](http://www.k-apt.go.kr/cmmn/kaptworkintro.do)
- 추가적으로 더 줄일 수 있는 feature를 찾아야 한다.

In [21]:
raw_data = raw_data[['거래금액(만원)','uid','단지명','전용면적(㎡)','층',
                     '건축년도','계약년월일','연','월','일',
                     '시','군','구','번지','본번','부번','도로명']]

In [22]:
raw_data

,거래금액(만원),uid,단지명,전용면적(㎡),층,건축년도,계약년월일,연,월,일,시,군,구,번지,본번,부번,도로명
0,"59,500",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,7,1988,2006-03-10,2006,3,10,서울특별시,강남구,개포동,655-2,655,2,언주로 103
1,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,6,1988,2006-03-29,2006,3,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
2,"67,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,9,1988,2006-04-29,2006,4,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
3,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,4,1988,2006-06-01,2006,6,1,서울특별시,강남구,개포동,655-2,655,2,언주로 103
4,"72,250",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,5,1988,2006-10-20,2006,10,20,서울특별시,강남구,개포동,655-2,655,2,언주로 103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061830,"44,500",서울특별시중랑구중화동한신2,한신2,59.76,15,1998,2019-08-08,2019,8,8,서울특별시,중랑구,중화동,450,450,0,동일로 752
1061831,"35,000",서울특별시중랑구중화동한영(101),한영(101),84.69,7,2003,2019-09-03,2019,9,3,서울특별시,중랑구,중화동,274-51,274,51,동일로144길 74
1061832,"25,800",서울특별시중랑구중화동한영(102),한영(102),57.18,6,2003,2019-05-20,2019,5,20,서울특별시,중랑구,중화동,274-75,274,75,동일로144길 74
1061833,"34,500",서울특별시중랑구중화동현대휴앤미,현대휴앤미,82.17,7,2007,2019-01-31,2019,1,31,서울특별시,중랑구,중화동,11,11,0,봉화산로27가길 23
1061834,"32,800",서울특별시중랑구중화동현대휴앤미(102동),현대휴앤미(102동),64.48,3,2007,2019-07-15,2019,7,15,서울특별시,중랑구,중화동,11-7,11,7,봉화산로27가길 19

In [25]:
apartment = pd.read_csv('./apart_price_raw_2006-2019.csv')

In [26]:
apartment

,거래금액(만원),uid,단지명,전용면적(㎡),층,건축년도,계약년월일,연,월,일,시,군,구,번지,본번,부번,도로명
0,"59,500",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,7,1988,2006-03-10,2006,3,10,서울특별시,강남구,개포동,655-2,655,2,언주로 103
1,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,6,1988,2006-03-29,2006,3,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
2,"67,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,9,1988,2006-04-29,2006,4,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
3,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,4,1988,2006-06-01,2006,6,1,서울특별시,강남구,개포동,655-2,655,2,언주로 103
4,"72,250",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,5,1988,2006-10-20,2006,10,20,서울특별시,강남구,개포동,655-2,655,2,언주로 103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061830,"44,500",서울특별시중랑구중화동한신2,한신2,59.76,15,1998,2019-08-08,2019,8,8,서울특별시,중랑구,중화동,450,450,0,동일로 752
1061831,"35,000",서울특별시중랑구중화동한영(101),한영(101),84.69,7,2003,2019-09-03,2019,9,3,서울특별시,중랑구,중화동,274-51,274,51,동일로144길 74
1061832,"25,800",서울특별시중랑구중화동한영(102),한영(102),57.18,6,2003,2019-05-20,2019,5,20,서울특별시,중랑구,중화동,274-75,274,75,동일로144길 74
1061833,"34,500",서울특별시중랑구중화동현대휴앤미,현대휴앤미,82.17,7,2007,2019-01-31,2019,1,31,서울특별시,중랑구,중화동,11,11,0,봉화산로27가길 23
1061834,"32,800",서울특별시중랑구중화동현대휴앤미(102동),현대휴앤미(102동),64.48,3,2007,2019-07-15,2019,7,15,서울특별시,중랑구,중화동,11-7,11,7,봉화산로27가길 19

In [27]:
def reduce_mem_usage(props):
    start_mem_usg = props.memory_usage().sum() / 1024**2 
    print("Memory usage of properties dataframe is :",start_mem_usg," MB")
    NAlist = [] # Keeps track of columns that have missing values filled in. 
    for col in props.columns:
        if props[col].dtype != object:  # Exclude strings

            # Print current column type
            print("******************************")
            print("Column: ",col)
            print("dtype before: ",props[col].dtype)

            # make variables for Int, max and min
            IsInt = False
            mx = props[col].max()
            mn = props[col].min()

            # Integer does not support NA, therefore, NA needs to be filled
            if not np.isfinite(props[col]).all(): 
                NAlist.append(col)
                props[col].fillna(mn-1,inplace=True)  

            # test if column can be converted to an integer
            asint = props[col].fillna(0).astype(np.int64)
            result = (props[col] - asint)
            result = result.sum()
            if result > -0.01 and result < 0.01:
                IsInt = True


            # Make Integer/unsigned Integer datatypes
            if IsInt:
                if mn >= 0:
                    if mx < 255:
                        props[col] = props[col].astype(np.uint8)
                    elif mx < 65535:
                        props[col] = props[col].astype(np.uint16)
                    elif mx < 4294967295:
                        props[col] = props[col].astype(np.uint32)
                    else:
                        props[col] = props[col].astype(np.uint64)
                else:
                    if mn > np.iinfo(np.int8).min and mx < np.iinfo(np.int8).max:
                        props[col] = props[col].astype(np.int8)
                    elif mn > np.iinfo(np.int16).min and mx < np.iinfo(np.int16).max:
                        props[col] = props[col].astype(np.int16)
                    elif mn > np.iinfo(np.int32).min and mx < np.iinfo(np.int32).max:
                        props[col] = props[col].astype(np.int32)
                    elif mn > np.iinfo(np.int64).min and mx < np.iinfo(np.int64).max:
                        props[col] = props[col].astype(np.int64)    

            # Make float datatypes 32 bit
            else:
                props[col] = props[col].astype(np.float32)

            # Print new column type
            print("dtype after: ",props[col].dtype)
            print("******************************")

    # Print final result
    print("___MEMORY USAGE AFTER COMPLETION:___")
    mem_usg = props.memory_usage().sum() / 1024**2 
    print("Memory usage is: ",mem_usg," MB")
    print("This is ",100*mem_usg/start_mem_usg,"% of the initial size")
    return props, NAlist

In [28]:
props, NAlist = reduce_mem_usage(apartment)

Memory usage of properties dataframe is : 137.71981048583984  MB
******************************
Column:  전용면적(㎡)
dtype before:  float64
dtype after:  float32
******************************
******************************
Column:  층
dtype before:  int64
dtype after:  int8
******************************
******************************
Column:  건축년도
dtype before:  int64
dtype after:  uint16
******************************
******************************
Column:  연
dtype before:  int64
dtype after:  uint16
******************************
******************************
Column:  월
dtype before:  int64
dtype after:  uint8
******************************
******************************
Column:  일
dtype before:  int64
dtype after:  uint8
******************************
******************************
Column:  본번
dtype before:  int64
dtype after:  uint16
******************************
******************************
Column:  부번
dtype before:  int64
dtype after:  uint16
******************************
___MEMORY USAGE AFTER COMPLETION:___
Memory usage is:  88.10021686553955  MB
This is  63.97062017058025 % of the initial size

In [29]:
apartment.to_csv("apartment_raw_2006-2019.csv", index=False)

In [23]:
raw_data.to_csv("apart_price_raw_2006-2019.csv",index=False)

In [25]:
apartment = pd.read_csv('./apart_price_raw_2006-2019.csv')

In [26]:
apartment

,거래금액(만원),uid,단지명,전용면적(㎡),층,건축년도,계약년월일,연,월,일,시,군,구,번지,본번,부번,도로명
0,"59,500",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,7,1988,2006-03-10,2006,3,10,서울특별시,강남구,개포동,655-2,655,2,언주로 103
1,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,6,1988,2006-03-29,2006,3,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
2,"67,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,9,1988,2006-04-29,2006,4,29,서울특별시,강남구,개포동,655-2,655,2,언주로 103
3,"60,000",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,4,1988,2006-06-01,2006,6,1,서울특별시,강남구,개포동,655-2,655,2,언주로 103
4,"72,250",서울특별시강남구개포동개포2차현대아파트(220),개포2차현대아파트(220),77.75,5,1988,2006-10-20,2006,10,20,서울특별시,강남구,개포동,655-2,655,2,언주로 103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061830,"44,500",서울특별시중랑구중화동한신2,한신2,59.76,15,1998,2019-08-08,2019,8,8,서울특별시,중랑구,중화동,450,450,0,동일로 752
1061831,"35,000",서울특별시중랑구중화동한영(101),한영(101),84.69,7,2003,2019-09-03,2019,9,3,서울특별시,중랑구,중화동,274-51,274,51,동일로144길 74
1061832,"25,800",서울특별시중랑구중화동한영(102),한영(102),57.18,6,2003,2019-05-20,2019,5,20,서울특별시,중랑구,중화동,274-75,274,75,동일로144길 74
1061833,"34,500",서울특별시중랑구중화동현대휴앤미,현대휴앤미,82.17,7,2007,2019-01-31,2019,1,31,서울특별시,중랑구,중화동,11,11,0,봉화산로27가길 23
1061834,"32,800",서울특별시중랑구중화동현대휴앤미(102동),현대휴앤미(102동),64.48,3,2007,2019-07-15,2019,7,15,서울특별시,중랑구,중화동,11-7,11,7,봉화산로27가길 19

------------------------------

In [ ]:
year_list = ["price_%d" % x for x in range(2006,2020)]
year_list

In [ ]:
year_list = [yr for yr in range(2006,2020)]
year_list

In [ ]:
%%time
for i in tqdm(range(2006,2020)):
    for k in d_list:
        k = price_table(i)

In [ ]:
%%time
for k in d_list:
    for i in tqdm(range(2006,2020)):
        k = price_table(i)

In [ ]:
for i in tqdm(range(2006,2020)):
    price_title = 'price_'+ '{}'.format(i)
#     price_table(i)
    'price_{i}'.format(i) = price_table(i)

In [ ]:
d_list=list(d.keys())
d_list

In [ ]:
for key, value in d.items():
    key = value
    print(key, value)

In [ ]:
d['price_2019'].dtypes

In [ ]:
for i in range(2009,2020):
    price_a='price_{}'.format(i)
    price_a = d['price_{}'.format(i)]